workflows:
  android-espresso:
    name: Android Espresso CI
    triggering:
      events:
        - push
        - pull_request
    environment:
      android:
        java: openjdk11
    scripts:
      - name: Run lint, unit tests & assemble debug APK
        script: ./gradlew --no-daemon lint test assembleDebug
      - name: Start emulator (if you have one)
        script: |
          adb start-server
          adb devices
      - name: Run instrumentation tests
        script: ./gradlew connectedAndroidTest --continue
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

